### ISSUE TITLE
ブロックの着色、不良ブロックの作成及びブロック設置時のアーム上昇の検証

### ISSUE THREAD

**Issue by sap2368** [KatLab-MiyazakiUniv/etrobocon2022#101]
## 完了条件
- 13個のブロック全てにシールを張り付ける
- 試走会の際に発覚した不良ブロックの再現と追加
- 不良ブロック設置の問題解消のためのアーム上昇の検証

## 実現方法
- 13個のブロック分のシールを印刷し、それぞれ張り付ける
- 新たにブロックを作成し、不良ブロックを再現する
- アーム上昇タスクの追加と、アームキープのタスクと兼ね合いの検証を行う

**Comment by KakinokiKanta** [comment]
不良ブロックを除く、全16個のブロックの完成

![Uploading 425A7156-04CD-410D-B4AB-BE723DBAA7BF.jpeg…]()
