### ISSUE TITLE
ブロックのOPPテープを張る

### ISSUE THREAD

**Issue by miyashita64** [KatLab-MiyazakiUniv/etrobocon2022#111]
## 完了条件
ブロックを光沢と粘着性を持たせる

## 実現方法
OPPテープを張る

**Comment by sugaken0528** [comment]
色識別での違いとかアームで持った時の違いを検証して欲しいです

**Comment by mutotaka0426** [comment]
> 色識別での違いとかアームで持った時の違いを検証して欲しいです

これ結局やらないって話にならなったっけ？
