### ISSUE TITLE
CIが失敗した際にSlackへ通知する

### ISSUE THREAD

**Issue by Takahiro55555** [KatLab-MiyazakiUniv/etrobocon2022#112]
## 完了条件
- CIがコケた際にSlackに通知する

## 実現方法
- Incoming Webhooksを利用する

## 関連資料（省略可）
- [Slackのカスタムインテグレーションが非推奨なったので移行した](https://zenn.dev/luna_chevalier/articles/dd79549e07e304a4274b)

**Comment by mutotaka0426** [comment]
これって何でslack通知処理をするの？
シェルを書くとして，GitHubActionsが実行する感じ？

あと，今気づいたけど，カメラシステムの方も同様のをよろしくお願いします

**Comment by Takahiro55555** [comment]
> これって何でslack通知処理をするの？ シェルを書くとして，GitHubActionsが実行する感じ？  

GitHub Actionsの処理(`.github/workflows/*.yaml`)にBashスクリプトとして記述する予定

> あと，今気づいたけど，カメラシステムの方も同様のをよろしくお願いします  

一応作ってます([#30](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/issues/30))

**Comment by mutotaka0426** [comment]
> GitHub Actionsの処理(`.github/workflows/*.yaml`)にBashスクリプトとして記述する予定

了解です！
いいと思います！

> 一応作ってます([#30](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/issues/30))

気づかなかった
お願いします
