### ISSUE TITLE
決め打ちボーナスブロック設置動作の設定

### ISSUE THREAD

**Issue by kawanoichi** [KatLab-MiyazakiUniv/etrobocon2022#113]
## 完了条件
- 決め打ちボーナスブロック設置動作の設定している

## 実現方法
- 以下で調整を行ったボーナスブロック設置調整のうち、LRで各１パターンずつGameAreaLeft(Right).csvファイルに上書きする
https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/issues/36

**Comment by mutotaka0426** [comment]
精度何割だったっけ
精度もissueに書いてて

**Comment by mutotaka0426** [comment]
回頭時間の測定＆設定は，どっちかっていうとカメラシステムのタスクでは？
どのみち，直接関係ないタスクは別にissueを立てた方がいいよ
関係ないのに依存関係を持たせるべきではないね

**Comment by sugaken0528** [comment]
各ベースエリア7割！

**Comment by mutotaka0426** [comment]
完了条件に，ボーナスブロック設置のコマンドファイルを8つ置くのがない

**Comment by mutotaka0426** [comment]
分かってると思うけど一応捕捉しておくと，ボーナスブロック設置コマンドファイル8つはカメラシステムに置いてね
そう考えると，カメラシステムの方にもチケット発行しないといけないかも
ほぼ同じ内容のチケットでいいと思うけど一部完了条件が異なるかな？

> * ボーナスブロック設置のコマンドファイルを8つ作成する(LR4パターンずつ)

はカメラシステムの方で，こっちは完了条件が，`GameAreaLeft.csv`と`GameAreaRight.csv`のボーナスブロック設置の部分を調整したコマンド（パラメータ）に変更するかな？
