### ISSUE TITLE
Rコースにおけるライントレースからボーナスブロック取得までの調整

### ISSUE THREAD

**Issue by sap2368** [KatLab-MiyazakiUniv/etrobocon2022#114]
## 完了条件
- ライントレース調整:精度90%,タイム10秒台
- ボーナスブロック取得調整:精度100%,タイム~12秒台
## 実現方法
- pwmなど各パラメータを調整し、精度を向上させる
- 検証はRコースで行い、走行体２を使用する
- ライントレース調整ファイル名はRight_02_調整日付(例:0901)とする
- ボーナスブロック取得調整ファイル名はToEndPointRight_02_調整日付(例:0901)とする

**Comment by mutotaka0426** [comment]
> * ライントレース調整ファイル名はRight_02_調整日付(例:0901)とする
> * ボーナスブロック取得調整ファイル名はToEndPointRight_02_調整日付(例:0901)とする

Rコースは調整してないんだし，`LineTraceAreaRight.csv`と`ToEndPointRight.csv`に直接書いていいんじゃない？
次のイテレーションで再調整するときに，今回のやつを残したかったら別名にして退避するとかでいいと思うよ
試走会2のやつを残したいのなら，そっちの方を退避させるべきじゃない？

あと，走行体2で調整をするのは良いと思うけど，もし余裕がありそうなら走行体1を使ったらどうなるか検証してほしい
せっかく2台走行体があるのに全く使わないのはもったいないし

**Comment by mutotaka0426** [comment]
あと，このチケットの完了条件にはしなくていいし，しなくてもいいけど，ショートカットを検討してみてもいいよ

安定性重視とは言え，安定してショートカットができそうならその方がいいしね
