### ISSUE TITLE
回頭と直進の布と紙の差を検証

### ISSUE THREAD

**Issue by sugaken0528** [KatLab-MiyazakiUniv/etrobocon2022#122]
## 完了条件
- 直進と回頭のpwm値ごとの距離の誤差を数値化する

## 実現方法
以下のpwm値と角度または距離の組み合わせパターンを紙と布で5回ずつ検証し、それぞれの誤差の平均値を出し、紙の場合と布の場合の差分を出す。
- 回頭(ブロック無し): pwm値[70,80,90,100]で回頭角度[45,90,135,180,225]
※紙のコースをブロック無しで回頭できるpwm値は70以上であり、270度以上の回頭は存在しない
- 回頭(ブロック有り): pwm[80,90,100]で回頭角度[45,90,135,180]
※紙のコースをブロック有りで回頭できるpwm値は80以上であり、225度以上の回頭は許可しない
- 直進(ブロック無し): pwm値[40,50,60,70,80,90,100]で直進距離[100,110,120,170,180,190]
※紙のコースをブロック無しで直進できるpwm値は40以上であり、ブロック無しで直進する距離F(110)と距離G(180)の+-10の距離を検証する
- 直進(ブロック有り): pwm値[60,70,80,90,100]で直進距離[100,110,120,170,180,190]
※紙のコースをブロック有りで直進できるpwm値は60以上であり、ブロック有りで直進する距離F(110)と距離G(180)の+-10の距離を検証する

距離Fと距離Gについては分析モデル2.1節参照

- スプレッドシートに測定結果(1040パターン)をまとめる
https://docs.google.com/spreadsheets/d/1oWvTgxDAb215ZaO_zJrXGAhXXGuTYOjqzEFAh92o0Ec/edit?usp=sharing

**Comment by mutotaka0426** [comment]
四人で回頭と直進両方やる感じ？
だったらいいけど，分けるならissueも分けた方がいいと思う

あと，完了条件にないけど，回頭に関しては動作時間と失敗率も測ってほしい
じゃないとカメラシステムの[ticket-46](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-camera-system/issues/46)ができない
それともこれは別のチケット？

**Comment by sugaken0528** [comment]
4人で回頭と直進両方やるで
コストに関しては別チケットです
