### ISSUE TITLE
カメラからpythonを使用して画像を取得、保存をできるようにする

### ISSUE THREAD

**Issue by kawanoichi** [KatLab-MiyazakiUniv/etrobocon2022#39]

**Comment by kawanoichi** [comment]
##完了条件
-カメラシステムから画像を読み込める
-読み込んだ画像を保存できる

**Comment by Takahiro55555** [comment]
WSLからのカメラの画像取得って出来そう？

今、Pythonの環境構築をしているんだけど、WSLから取得できれば環境構築の減るので気になった次第です...
