### ISSUE TITLE
試走会1でやること、持っていくもの

### ISSUE THREAD

**Issue by Takahiro55555** [KatLab-MiyazakiUniv/etrobocon2022#54]
## カメラシステム
- [ ] カメラ画像カメラ角度を変更しながらを複数取得する
- [ ] 研究室のカメラと会場のカメラの画像の差分を確認する（画像を保存する）

## 走行システム
- [ ] キャリブレーションから完成している箇所まで

## コース関連
- [x] ブロックの重さを測る
- [x] ブロックの静止最大摩擦係数と動摩擦係数を計測する
- [x] 研究室独自のブロックと試走会のブロックの色の差分を確認する
- [x] コースの距離を計測する（ゲームエリアのサークル間の黒線の長さを測れば、良さそう？）
    - [x] 印刷したコースと実際のコースのずれがないかを確認する
- [ ] 走行体のカラーセンサーで会場のコースの色を取得する
    - [x] ライントレース中の色を全て取得する
    - [ ] コース特定の箇所に直接走行体を置いて計測する
-  [ ] 走行の度に動画を撮り、コースアウト箇所等を分析できるようにする

## 持っていくもの
- [x] 走行体 x 2
    - [x] 複数の車に分散して運ぶ
    - [x] バッテリー
    - [x] 充電器
- [x] 本番で使用するPC
- [x] 小型Wi-Fiルータ
- [x] メジャー
- [x] カメラ
- [x] モデル
- [x] マジックハンド
- [x] ブロック
- [x] ばねはかり（最大500g程度まで計測できれば十分）
- [x] iPad(撮影用)
- [x] 摩擦係数計測キット（コースの布と本番のブロックの摩擦係数を計測するため）
    - [x] 板(30cm x 30cm 以上の大きさ)
    - [x] コースの布
    - [x] 板の傾きを計測できる機器（スマホの水平器から数値を確認できればOK）

## チーム分け
- 走行チーム（3人 @sugaken0528 @sap2368 @KakinokiKanta ）
    - スタート係
    - 拾う係
    - 撮影係
- カメラシステムチーム（3人 @Takahiro55555 @kodama0720 @kawanoichi ）
- 計測チーム（メジャーやはかり等）
   - カメラシステムチームと兼任
- モデル相談係（2人 @mutotaka0426 @miyashita64 ）

**Comment by mutotaka0426** [comment]
https://user-images.githubusercontent.com/56989154/180590157-d9df0e9c-669f-4fce-a48f-84eca1a1adf0.MOV

https://user-images.githubusercontent.com/56989154/180590165-b64f8af5-6b0a-4257-a26b-a23383c75cb1.MOV

https://user-images.githubusercontent.com/56989154/180590170-59874156-d88c-4dd5-85fc-53344f39efe5.MOV

https://user-images.githubusercontent.com/56989154/180590177-fb5f98db-78ac-48e3-9bd2-a3b9ca9caac3.MOV

https://user-images.githubusercontent.com/56989154/180590185-2b118d2c-13e9-47cb-abd0-de06b7b933df.MOV

https://user-images.githubusercontent.com/56989154/180590188-365d15e1-6501-45ea-84f2-d0fa58191230.MOV

**Comment by mutotaka0426** [comment]
緑1

https://user-images.githubusercontent.com/56989154/180590409-3557c995-92cf-4c52-94ea-1f238f9e9f38.MOV

緑2

https://user-images.githubusercontent.com/56989154/180590418-736b62b9-4d67-4f1a-b64b-e7abf6d7e111.MOV

青(同じので2かいそくてい)

https://user-images.githubusercontent.com/56989154/180590423-24e23077-0480-433c-a2ff-3e0a66972bea.MOV

https://user-images.githubusercontent.com/56989154/180590427-f9b19841-0477-4539-92a7-b04386c88b47.MOV

黄

https://user-images.githubusercontent.com/56989154/180590430-beda4e6f-34c1-48b2-97fe-05d74895f2dc.MOV

赤

https://user-images.githubusercontent.com/56989154/180590435-87e92d20-8915-46c6-bcc3-ad9a2b42d09a.MOV

黒

![ 180590449 をアップロード中...]

**Comment by mutotaka0426** [comment]
キャリブレーション処理の中で、アームを下げる処理を入れる

**Comment by kodama0720** [comment]
[各色のRGB値測定](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/files/9175253/default.txt)
[RGB値取得しつつライントレース](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/files/9175254/runcolor.txt)

**Comment by KakinokiKanta** [comment]
[ゴール後からボーナスブロック運搬までのRGB値(1).csv](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/files/9205627/RGB.1.csv)
[ゴール後からボーナスブロック運搬までのRGB値(2).csv](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/files/9205628/RGB.2.csv)

**Comment by Takahiro55555** [comment]
コースのサイズ計測結果![image](https://user-images.githubusercontent.com/31930148/181444347-e8f3d501-0fd3-4563-8b96-f5b485c18af1.png)
