### ISSUE TITLE
ライントレースエリアの計測・調整

### ISSUE THREAD

**Issue by sap2368** [KatLab-MiyazakiUniv/etrobocon2022#66]
## 完了条件
- 走行タイムと精度を測る
- 試走会との比較を行う
## 実現方法
- Lコースのみで計測する
- 走行体によるパラメータの差違も確認する
- バッテリーは、機体番号とバッテリー番号を揃える。

**Comment by mutotaka0426** [comment]
最低でも走行体につき10回ずつはやって欲しいけど，余裕があるなら多めによろしく
