### ISSUE TITLE
カラーブロックの完成

### ISSUE THREAD

**Issue by KakinokiKanta** [KatLab-MiyazakiUniv/etrobocon2022#68]
## 完了条件
- (運搬用)全12個のカラーブロックの作成
- ベースサークル上のブロック作成

## 実現方法
- 摩擦を考慮したブロック
- カラーシール作成と貼り付け(できれば)

**Comment by KakinokiKanta** [comment]
[角度測定結果.csv](https://github.com/KatLab-MiyazakiUniv/etrobocon2022/files/9208205/default.csv)

**Comment by Takahiro55555** [comment]
実験の結果、OPPテープを底面の素材に採用するのが最適であるという結論に至った。
また、OPPテープの幅が足りずブロックの底面をカバーしきれないという問題を解消するために、十字に2枚張ることとする。
それでも、試走会の平均11度には及ばないため、重量を約117g(ビー玉3個、おはじき8枚)にし、規約の範囲内で本番のブロックの滑りに近づけることとする。

ブロックの底面の素材 | 平均 | 1 | 2 | 3 | 4 | 5
-- | -- | -- | -- | -- | -- | --
茶色のクラフトテープ | 38 | 37 | 39 |   |   |  
靴下（ポリエステル・ポリウレタン） | 23.5 | 23 | 24 |   |   |  
合皮はぎれ・黒（裏面） | 32.5 | 32 | 33 |   |   |  
合皮はぎれ・黒（表面） | 35 | 33 | 37 |   |   |  
バンダナ・ポリエステル（裏） | 23 | 22 | 26 | 21 |   |  
OPPテープ（重量約125g、ごく一部カバーできてない箇所あり） | 13.8 | 12 | 14 | 14 | 15 | 14
OPPテープ（重量約117g） | 12.6 | 13 | 13 | 12 | 12.5 | 12.5
OPPテープ（重量約117g、進行方向に対して直角にテープの端があり、抵抗が増えそうな向き） | 12.5 | 12.5 | 12.5 |   |   |  
OPPテープ・十字重ね貼り（重量約117g） | 12.8 | 13 | 12 | 12 | 13.5 | 13.5
OPPテープ・十字重ね貼り（重量約125g） | 13 | 12.5 | 13.5 | 12 | 13 | 14

**Comment by mutotaka0426** [comment]
テープを張ったブロックは，コースの段差（のりしろのところ）を通過できる？

**Comment by Takahiro55555** [comment]
追加購入が必要なもの
- おもり
  - ガラス製ビー玉（大サイズ）：36個（9袋？）
  - ガラス製おはじき：96個（4袋？）
 
いずれも、CanDo（百円ショップ）で購入予定

**Comment by Takahiro55555** [comment]
> テープを張ったブロックは，コースの段差（のりしろのところ）を通過できる？

自分は確認してないです。

**Comment by KakinokiKanta** [comment]
> テープを張ったブロックは，コースの段差（のりしろのところ）を通過できる？

自分が確認したところ、普通に通過できました。

**Comment by Takahiro55555** [comment]
残り2個
![image](https://user-images.githubusercontent.com/31930148/183423973-343537dd-6152-436d-8440-df87f852b497.jpeg)
