### ISSUE TITLE
ゲームエリア内動作のパラメータ調整

### ISSUE THREAD

**Issue by KakinokiKanta** [KatLab-MiyazakiUniv/etrobocon2022#77]
## 完了条件
- 2動作（3ノード）の組み合わせで9割

## 実現方法
- 全11動作でのパラメータの調整
- 走行体2でLコースで調整

**Comment by kodama0720** [comment]
移動 | 動作 | 開始状態 | 終了状態
-- | -- | -- | --
中点→交点 | 方向転換→色までライントレース+交差点まで調整 | カラーセンサがエッジ上 | タイヤの中心がエッジの交差点上
中点→ブロ | 方向転換→縦調整→距離直進 | タイヤの中心がブロ側のエッジ上 | タイヤの中心がブロの中心
中点→中点 | 方向転換→黒まで直進(斜め)→斜め調整 |   |  
ブロ→交点 | 方向転換→色まで直進(斜め)+交差点まで調整 |   |  
交点→中点 | 方向転換→縦調整→距離でライントレース |   |  
交点→ブロ | 方向転換→縦調整→方向転換→距離直進（斜め） |   |  
ブロ→中点 | 方向転換→黒まで直進+距離直進 |   |  
方向転換 |   | 不定 | 不定
設置動作 | 方向転換（設置）→ |   |

**Comment by mutotaka0426** [comment]
ゲームエリア内動作の終了位置や調整位置を図で書いたものです
雑だしすべては書いてないけど，分からないところがあったら聞いてください

![ゲーム攻略動作の図](https://user-images.githubusercontent.com/56989154/182824835-0d05a575-22f3-4ceb-8e80-58f20920ee9b.png)

**Comment by miyashita64** [comment]
ノード間移動*2の成功率に加えて、各ノード間移動を構成する動作(距離/色までライントレース(縦、斜め)、距離/色まで直進(縦、斜め)、黒線分直進(縦、斜め))についても、計測してほしいです。

**Comment by sap2368** [comment]
現状報告
各種パラメータ調整を一通り調整し終えた
金土日月で成功率、動作時間共に計測しつつ再調整の予定
