### ISSUE TITLE
尻尾カメラの検証

### ISSUE THREAD

**Issue by Takahiro55555** [KatLab-MiyazakiUniv/etrobocon2022#78]
## 完了条件
- 尻尾カメラから画像を取得できる
- 尻尾カメラの画像からコースの直線に対する走行体の角度を取得できる

## 実現方法
- Raspberry Piから画像を取得する
- 画像に映っている直線から走行体の角度を取得する
- 画像処理には、OpenCVを用いる

**Comment by Takahiro55555** [comment]
## 検証内容
- `raspistill`コマンドを用いた尻尾カメラ画像の撮影
- 尻尾カメラ画像の歪み補正
- 尻尾カメラ画像の台形補正
- 尻尾カメラ画像から黒線を検出する
- 検出した黒線の角度を算出する

### できてないこと
- 走行中に自動的に尻尾カメラ画像を取得、保存すること

## 検証結果
### 尻尾カメラ画像の歪み補正
尻尾カメラ画像の歪補正を行ったが、黒線検出では用いていない。
理由としては、補正後の画像で外枠の部分が黒色で塗り分されてしまい、黒線検出の際に邪魔なためである。

![スライド1](https://user-images.githubusercontent.com/31930148/184792776-a88f2aac-7e7e-474f-9e40-6695f09c7d3b.PNG)

### 尻尾カメラ画像の台形補正・黒線の検出
台形補正の際のパラメータの算出に、以下の画像に示すArUcoマーカを利用した。
![スライド2](https://user-images.githubusercontent.com/31930148/184793055-444da989-964a-4406-92ce-2ecd4e9ad668.PNG)

台形補正を行う際、コースの歪みが悪影響を及ぼすことが分かった。
台形補正後の画像を以下に示す。なお、検出した黒線を水色で囲んでいる。
![スライド3](https://user-images.githubusercontent.com/31930148/184793151-dd3e6b83-fe50-4118-a95d-ffbd89258d47.PNG)

簡易的にではあるが、検出した黒線を直線で近似し角度を算出した画像を以下に示す。
![スライド4](https://user-images.githubusercontent.com/31930148/184793283-0fccdf6c-3b31-4fcd-9e1e-e23d581ed740.PNG)
![スライド5](https://user-images.githubusercontent.com/31930148/184793288-4446feb1-4ea4-4b94-8737-e1ac4018bebe.PNG)


## 添付資料
- [ソースコード](https://github.com/KatLab-MiyazakiUniv/etrobocon2022-raspike-tail-camera-playground.py)
※何も考えず、別リポジトリを作ってしまったが、本来は`etrobocon2022`にPushするべきであったと考える。

**Comment by mutotaka0426** [comment]
お疲れ様！
とりあえず直線の検出まではできそうだね
どれくらいのfpsで画像を取得できるのか（走行に影響を及ぼさないのか）調査するのと，どうやって走行システムに組み込むかってところを解決出来たら，実用できそうかな？

あとは，試走会で画像を取得して台形補正かけても歪みが出るかどうかは調査する必要がありそうやね
リポジトリの件は，とりあえず調査の間はこのままでもいいと思うよ
