### ISSUE TITLE
試走会2

### ISSUE THREAD

**Issue by kodama0720** [KatLab-MiyazakiUniv/etrobocon2022#85]
## やること
- ライントレースエリアを走行する
- ゲーム攻略する
- 尻尾カメラの画像を取得する
- Webカメラの画像を取得する
- モデル相談する

## 持っていくもの
- [ ] 走行体1,2
- [ ] バッテリー
- [ ] カメラ
- [ ] マジックハンド
- [ ] ブロック
- [ ] パソコン
- [ ] wi-fi環境
- [ ] iPad
- [ ] 尻尾カメラキャリブレーション用板

## チーム
- カメラ（尻尾・Web）　上田
- 走行調整（ライントレース・ビンゴ）　菅・児玉・柿木・榊原
- モデル　武藤・宮下・河野

## 試走会前にやること
- [ ] ライントレースのパラメータを最新にする
- [ ] 端点サークルまでの調整
- [ ] ゲームエリアのコマンドを作る
- [ ] 不要なブランチを消す
- [ ]  試走会のブランチを作る
- [ ] バッテリー残量の表示
- [ ] 尻尾カメラの固定
- [ ] 尻尾カメラのピント調整
- [ ] 尻尾カメラの録画機能の実装
- [ ] ラズパイの接続方法を確認する
- [ ] 充電をマックスにする（当日0時まで）
- [ ] モデル相談会で聞くことを決める

## 流れ
- 他チームとの話し合い
- ライントレースの確認
- ゲームエリアの確認
- 通しの確認
- カメラ撮影
- 調整

**Comment by kawanoichi** [comment]
# 画像の取得方法を以下に示す
①PCにUSBカメラを接続する
②カメラIDを確認する
~~~
$ python camera_insterface.py
~~~
③カメラから画像を取得し、保存する   
~~~
$ python camera_insterface.py -id <カメラID>
~~~


![スクリーンショット (192)](https://user-images.githubusercontent.com/96767490/178712966-71e20132-8091-4a7f-82db-630347400da0.png)
