### ISSUE TITLE
尻尾カメラのピント調整・固定

### ISSUE THREAD

**Issue by Takahiro55555** [KatLab-MiyazakiUniv/etrobocon2022#92]
## 完了条件
- 尻尾カメラからコースの画像を鮮明に撮影できるようにする
- 尻尾カメラが外れないように固定する

## 実現方法
- 尻尾カメラからコースの画像を鮮明に撮影できるようにする
  - カメラ本体のレンズを回転させ、ピントの調整を行う
  - ``` 
        ssh katlab@katlab-et-pi4b8gb-01 -XC
        libcamera-vid -t0 -p=0.25,0.25,1,1 --qt-preview --width 1640 --height 1232 && libcamera-still -n -o tmp.png
    ```
- 尻尾カメラが外れないように固定する
  - 輪ゴム及び、テープ等を用いてカメラを固定する
  - カメラ固定用の3Dプリントパーツを作成する

**Comment by Takahiro55555** [comment]
完了

**Comment by mutotaka0426** [comment]
> 完了

両方？

**Comment by Takahiro55555** [comment]
> > 完了
> 
> 両方？

YES
